[package]
name = "desruction-studios/state"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"
Trove = "sleitnick/trove@1.5.1"
Signal = "sleitnick/signal@2.0.3"
UniqueKey = "destruction-studios/uniquekey@1.0.4"