[package]
name = "destruction-studios/state"
version = "0.5.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["src/Tests", "TestEZ", "test.project.json"]

[dependencies]
Promise = "evaera/promise@4"
UniqueKey = "destruction-studios/uniquekey@1.0.4"